// Generated by @lattice-php/vite-svg-sprite. Do not edit.

export const iconNames = [
  "align-center",
  "align-justify",
  "align-left",
  "align-right",
  "arrow-down",
  "arrow-left-to-line",
  "arrow-right-to-line",
  "arrow-up",
  "bell",
  "bold",
  "calendar",
  "check",
  "chevron-down",
  "chevron-left",
  "chevron-right",
  "chevrons-up-down",
  "circle-alert",
  "circle-check",
  "circle-help",
  "circle-user",
  "circle-x",
  "clock",
  "code",
  "code-xml",
  "columns-2",
  "columns-3",
  "copy",
  "corner-down-right",
  "external-link",
  "eye",
  "eye-off",
  "filter",
  "fingerprint",
  "grip-vertical",
  "heading",
  "heading-1",
  "heading-2",
  "heading-3",
  "heading-4",
  "heading-5",
  "heading-6",
  "highlighter",
  "image",
  "images",
  "info",
  "italic",
  "key-round",
  "layers",
  "layout-dashboard",
  "layout-template",
  "link",
  "list",
  "list-ordered",
  "list-plus",
  "loader-2",
  "log-out",
  "logo",
  "minus",
  "more-horizontal",
  "move-vertical",
  "panel-left",
  "pencil",
  "pencil-line",
  "pilcrow",
  "plus",
  "quote",
  "redo-2",
  "rotate-ccw",
  "rows-3",
  "search",
  "send",
  "settings",
  "shield-alert",
  "shield-check",
  "smartphone",
  "smile",
  "square",
  "strikethrough",
  "table",
  "trash-2",
  "underline",
  "undo-2",
  "usb",
  "users",
  "x",
] as const;

export type IconName = (typeof iconNames)[number];

declare module "@lattice-php/ui" {
  interface KnownIcons {
    "align-center": true;
    "align-justify": true;
    "align-left": true;
    "align-right": true;
    "arrow-down": true;
    "arrow-left-to-line": true;
    "arrow-right-to-line": true;
    "arrow-up": true;
    bell: true;
    bold: true;
    calendar: true;
    check: true;
    "chevron-down": true;
    "chevron-left": true;
    "chevron-right": true;
    "chevrons-up-down": true;
    "circle-alert": true;
    "circle-check": true;
    "circle-help": true;
    "circle-user": true;
    "circle-x": true;
    clock: true;
    code: true;
    "code-xml": true;
    "columns-2": true;
    "columns-3": true;
    copy: true;
    "corner-down-right": true;
    "external-link": true;
    eye: true;
    "eye-off": true;
    filter: true;
    fingerprint: true;
    "grip-vertical": true;
    heading: true;
    "heading-1": true;
    "heading-2": true;
    "heading-3": true;
    "heading-4": true;
    "heading-5": true;
    "heading-6": true;
    highlighter: true;
    image: true;
    images: true;
    info: true;
    italic: true;
    "key-round": true;
    layers: true;
    "layout-dashboard": true;
    "layout-template": true;
    link: true;
    list: true;
    "list-ordered": true;
    "list-plus": true;
    "loader-2": true;
    "log-out": true;
    logo: true;
    minus: true;
    "more-horizontal": true;
    "move-vertical": true;
    "panel-left": true;
    pencil: true;
    "pencil-line": true;
    pilcrow: true;
    plus: true;
    quote: true;
    "redo-2": true;
    "rotate-ccw": true;
    "rows-3": true;
    search: true;
    send: true;
    settings: true;
    "shield-alert": true;
    "shield-check": true;
    smartphone: true;
    smile: true;
    square: true;
    strikethrough: true;
    table: true;
    "trash-2": true;
    underline: true;
    "undo-2": true;
    usb: true;
    users: true;
    x: true;
  }
}
